// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $AllMethods from "./islands/AllMethods.ts";
import * as $Button from "./islands/Button.tsx";
import * as $Calculator from "./islands/Calculator.tsx";
import * as $Forms from "./islands/Forms.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/AllMethods.ts": $AllMethods,
    "./islands/Button.tsx": $Button,
    "./islands/Calculator.tsx": $Calculator,
    "./islands/Forms.tsx": $Forms,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
